In [7]:
import pandas as pd

df = pd.read_csv('../data/processed/titanic_selected.csv')
df.head()

   survived  pclass     sex      fare  familySize embarked    age
0         1       1  female  211.3375           0        S  29.00
1         1       1    male  151.5500           3        S   0.92
2         0       1  female  151.5500           3        S   2.00
3         0       1    male  151.5500           3        S  30.00
4         0       1  female  151.5500           3        S  25.00

**Revisión de valores nulos**

In [2]:
df.isnull().sum()

survived        0
pclass          0
sex             0
fare            1
familySize      0
embarked        2
age           263
dtype: int64

Se decide rellenar ese único valor nulo en la variable Fare con la mediana y no con la media, ya que con base en su distribución (histograma) se observa que hay tarifas relativamente altas, lo cual distorsiona la media , no siendo una representación adecuada de las tarifas

In [8]:
df['fare'] = df['fare'].fillna(df['fare'].median())

Se rellenan los valores nulos en la variable 'age' con la mediana. En contraste con la variable fare, la edad presenta una distribución aproximadamente normal, hay una diferencia relativamente baja (1.8) entre la media y la mediana, por lo que ambas son buenas representaciones del conjunto de datos.

In [9]:
df['age'] = df['age'].fillna(df['age'].median())

**Codificación de variables numéricas**

In [10]:
df = pd.get_dummies(df, columns=['sex','embarked'], drop_first=True, dtype = int)
df

,survived,pclass,fare,familySize,age,sex_male,embarked_Q,embarked_S
0,1,1,211.3375,0,29.00,0,0,1
1,1,1,151.5500,3,0.92,1,0,1
2,0,1,151.5500,3,2.00,0,0,1
3,0,1,151.5500,3,30.00,1,0,1
4,0,1,151.5500,3,25.00,0,0,1
...,...,...,...,...,...,...,...,...
1304,0,3,14.4542,1,14.50,0,0,0
1305,0,3,14.4542,1,28.00,0,0,0
1306,0,3,7.2250,0,26.50,1,0,0
1307,0,3,7.2250,0,27.00,1,0,0
1308,0,3,7.8750,0,29.00,1,0,1

In [11]:
df.to_csv('../data/processed/titanic_transformation.csv', index=False)